### Exercício 1

In [6]:
def substring_rep(input):

    if not isinstance(input, str):
        print('Input não é string')
        return

    Dict = {}
    substring = ''

    for x in range(len(input)):
        
        substring += input[x]        
        substring_repeat = 0        

        for y in range(len(input)):            
            if substring == input[y:y+x+1]:            
                substring_repeat += 1
            
        Dict.update({substring_repeat:substring})
    
    return(Dict)

In [7]:
substring_rep('abcccc')

{1: 'abcccc'}

In [18]:
def substringmaxima(s: str):
    posicao=0
    maximo=0
    for i in range(len(s)):
        #print (i)
        pedaco = s[posicao:i+1]
        #print (pedaco)
        if(len(pedaco) == len(set(pedaco))): #sets não têm elementos repetidos!
            maximo = max(len(pedaco),maximo)
        else:
            posicao += 1
    return (maximo,pedaco) 

In [19]:
substringmaxima('aabaaaagbdn')

(5, 'agbdn')

In [21]:
numero = input("digite um número")
#converti para inteiro porque pede para "ler um número inteiro", seja float ou seja string
try:
    print(f"Número: {int(numero)}")
    print(f"Antecessor: {int(numero) - 1}")
    print(f"Sucessor: {int(numero) + 1}")
except:
    print("Você não passou um número válido")

digite um número3.6
Você não passou um número válido


### Exercício 2

In [3]:
def antecessorsucessor(entrada):
    #num = int(input('Digite um número:'))
    num = int(entrada)
    su = num + 1
    an = num - 1
    return(num, an, su)

In [4]:
antecessorsucessor(3)

(3, 2, 4)

In [5]:
antecessorsucessor('3') #str

(3, 2, 4)

In [6]:
antecessorsucessor(3.6) #float

(3, 2, 4)

In [22]:
def valores(x):
    x = int(float(x))
    return x-1, x+1
valor = 3.6
ant,pos = valores(valor)
print(valor, ant, pos)

3.6 2 4


In [23]:
import pandas as pd
import numpy as np
from math import floor
x = input('informe um número' )
y = {'numero_inteiro':[x]}

df = pd.DataFrame(y)
df = df.set_index([pd.Index(['numero:'])])

df['numero_inteiro'] = floor(df['numero_inteiro'])

df['numero_antecessor'] = floor(df['numero_inteiro']-1)
df['numero_sucessor'] = floor(df['numero_inteiro']+1)

print(df[['numero_inteiro','numero_antecessor','numero_sucessor']])

informe um número3.6
         numero_inteiro  numero_antecessor  numero_sucessor
numero:               3                  2                4


### Exercício 3

In [28]:
def most_frequent(s):
    # Criar dicionário com frequência dos itens
    hist = {} #dicionário
    for x in s:
        hist[x] = hist.get(x, 0) + 1
        #print(hist)

    t = [] # lista
    for x, freq in hist.items():
        t.append((freq, x))
    #print(t)
    
    t.sort(reverse=True)

    resposta = []
    for freq, x in t:
        resposta.append(x)
    #print(resposta)

    return resposta

In [31]:
def most_frequent(s: str):
    s = set(s)
    lista = list(s)
    lista.sort(reverse=True)
    return print(lista)
sValor = input('Infome uma string:')
most_frequent(sValor);

Infome uma string:aaaabc
['c', 'b', 'a']


In [29]:
most_frequent('abbbgggggg')

['g', 'b', 'a']

### Exercício 4

In [43]:
def digit_1_counter(input):
    counter = 0
    for x in reversed(range(input+1)): 
        #print(x)
        for y in range(len(str(x))):
            if str(x)[y] == '1':
                counter += 1            
    print(counter)
digit_1_counter(13)

6


In [44]:
digit_1_counter(139)

74


In [45]:
def conteum(n: int):
        m = len(str(n))
        if m == 1:
            return 0 if n == 0 else 1 # já sabemos a resposta nesse caso
        
        dezena = 10 ** (m - 1)
        #print(dezena)
        num_digits_dezena = (m - 1) * 10 ** (m - 1)
        #print(num_digits_dezena)
        num_ones_dezena = num_digits_dezena // 10
        #print(num_ones_dezena)
        primeiro_digit = n // (10 ** (m-1))
        #print(primeiro_digit)
        resto = n % (10 ** (m-1))
        #print(resto)
        #print(primeiro_digit + (10 ** (m - 1)))
        #print(conteum(resto))
        if primeiro_digit > 1:
            return num_ones_dezena * primeiro_digit + (10 ** (m - 1)) + conteum(resto)
        else:
            return num_ones_dezena + conteum(resto) + (resto + 1)

In [46]:
conteum(139)

74

### Exercício 5

In [47]:
import numpy as np
lin = input("Informe o tamanho da linha: ")
col = input("Informe o tamanho da coluna: ")
aleatorios = np.random.randint(1000, size=(int(lin), int(col)))
print(aleatorios)

Informe o tamanho da linha: 3
Informe o tamanho da coluna: 4
[[572 419 728 359]
 [131  42 215 661]
 [456 130 233 764]]


In [50]:
import random
n = int(input('Digite a dimensão n da matriz: ')) 
m = int(input('Digite a dimensão m da matriz: ')) 
matriz = []
for i in range(n):
    linha = []
    for j in range(m):
        linha.append(random.randint(5, 50)) # random.randint(start, stop)
    matriz.append(linha)
print(matriz)

Digite a dimensão n da matriz: 3
Digite a dimensão m da matriz: 4
[[21, 16, 14, 25], [16, 37, 8, 15], [43, 17, 40, 35]]


### Exercício 7

In [52]:
import datetime
from datetime import date

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

def days_until_birthday(birthday):
    """How long until my next birthday?"""
    today = datetime.datetime.today()
    # when is my birthday this year?
    next_birthday = datetime.datetime(today.year, birthday.month, birthday.day)

    # if it has gone by, when will it be next year
    if today > next_birthday:
        next_birthday = datetime.datetime(today.year+1, birthday.month, birthday.day)

    # subtraction on datetime objects returns a timedelta object
    delta = next_birthday - today
    return delta.days

#birthday = datetime.datetime.now()
birthday = datetime.datetime(2001,5,3)
print('Idade:', end=' ')
print(calculate_age(birthday))
print('Dias até próximo niver:', end=' ')
print(days_until_birthday(birthday))

Idade: 21
Dias até próximo niver: 35


In [55]:
import datetime
from datetime import date
today = datetime.datetime.today()
today

datetime.datetime(2023, 3, 28, 15, 28, 45, 666052)

### Exercício 8 - dúvida migração

In [25]:
import pandas as pd
base = pd.read_csv('/Users/anamees/Desktop/migracao.csv', delimiter=',')
base

Produto  Preço
0     Suco   14.9
1    Carne  44,56
2  D'ajuda    3.9

In [57]:
base = pd.read_csv('/Users/anamees/Desktop/migracao.csv', delimiter=';')
base

Produto,Preço
0      Suco,14.9
1  Carne,"44,56"
2    D'ajuda,3.9